[versions]
log4j = "2.23.1"
protocol = "3.0.0.Beta11-SNAPSHOT"

[libraries]
# Logging
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
log4j-slf4j2-impl = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4j" }

# Network
network = { group = "org.cloudburstmc.netty", name = "netty-transport-raknet", version = "1.0.0.CR3-SNAPSHOT"}

# Protocol
bedrock-codec = { group = "org.cloudburstmc.protocol", name = "bedrock-codec", version.ref = "protocol"}
bedrock-connection = { group = "org.cloudburstmc.protocol", name = "bedrock-connection", version.ref = "protocol"}

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.0.0" }
git = { id = "com.gorylenko.gradle-git-properties", version = "2.4.2" }

[bundles]
log4j = [ "log4j-api", "log4j-core", "log4j-slf4j2-impl" ]
protocol = [ "bedrock-codec", "bedrock-connection" ]